services:
  py-web-app:
    container_name: homer-simpson-quotes-container
    image: 901407365530.dkr.ecr.eu-north-1.amazonaws.com/python/python_app:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis-db
    env_file:
      - ./env_vars/.redis_endpoint
      - ./env_vars/.redis_port
    stop_grace_period: 30s
    restart: unless-stopped

  redis-db:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    stop_grace_period: 30s
    restart: unless-stopped

volumes:
  redis-data:
