# name: Infrastructure Provision and Deploy

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   provision:
#     name: Provision Infrastructure
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.3.5

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Plan
#         id: plan
#         run: terraform plan -out=tfplan

#       - name: Upload Terraform plan
#         uses: actions/upload-artifact@v2
#         with:
#           name: tfplan
#           path: tfplan

#   deploy:
#     name: Deploy Docker Image
#     runs-on: ubuntu-latest
#     needs: provision
#     if: ${{ github.event_name == 'workflow_dispatch' }}
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.3.5

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Download Terraform plan
#         uses: actions/download-artifact@v2
#         with:
#           name: tfplan

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Apply
#         run: terraform apply tfplan